// DataImport demonstrates the CxSAST-to-Cx1 data migration import cycle: taking an
// export.zip + encryption key generated by the separate CxSAST exporter tool, and
// feeding it into Cx1 via the async start -> poll pattern used by every long-running
// operation in this library (reports, exports, and scans all follow the same shape):
//   - StartMigration reads the zip/key and kicks off the import, returning an ID
//   - ImportPollingByID blocks, polling that ID until the import reaches a terminal
//     status
//
// This example does not build a project-to-application mapping (see StartMigration's
// second argument); a real migration would typically supply one so imported CxSAST
// projects land under the right Cx1 Applications instead of ungrouped.
package main

import (
	"flag"
	"net/http"
	"os"

	"github.com/cxpsemea/Cx1ClientGo"
	"github.com/sirupsen/logrus"
	easy "github.com/t-tomalak/logrus-easy-formatter"
)

func main() {
	logger := logrus.New()
	logger.SetLevel(logrus.InfoLevel)
	myformatter := &easy.Formatter{}
	myformatter.TimestampFormat = "2006-01-02 15:04:05.000"
	myformatter.LogFormat = "[%lvl%][%time%] %msg%\n"
	logger.SetFormatter(myformatter)
	logger.SetOutput(os.Stdout)
	logger.Infof("Starting")
	logger.Info("This application requires an existing export.zip + encryption key, as generated from CxSAST using the cxsast export tool provided by Checkmarx.")

	key := flag.String("key", "Uo9B+aCL4Z1rhemrUzUEQLCj3hX15yHxx99FQ9+vyc8=", "The encryption key for a CxSAST Export Zip file")
	file := flag.String("file", "importData.zip", "The exporter-generated zip file")
	cx1client, err := Cx1ClientGo.NewClient(&http.Client{}, logger)
	if err != nil {
		logger.Fatalf("Error creating client: %s", err.Error())
	}

	// Load the CxSAST-exported archive into memory; StartMigration uploads its bytes directly.
	fileContents, err := os.ReadFile(*file)
	if err != nil {
		logger.Fatalf("Failed to read %v: %s", *file, err)
	}

	// Kick off the async import. The second argument is an optional project-to-application
	// mapping (as JSON bytes) - empty here, so every imported project lands ungrouped.
	importID, err := cx1client.StartMigration(fileContents, []byte{}, *key) // no project-to-app mapping
	if err != nil {
		logger.Fatalf("Failed to start migration: %s", err)
	}

	// Poll until the import reaches a terminal status (same request -> poll shape used
	// by scans, reports, and exports elsewhere in this library).
	result, err := cx1client.ImportPollingByID(importID)
	if err != nil {
		logger.Fatalf("Failed during polling: %s", err)
	}

	logger.Infof("Migration data import finished with status: %v", result)
}
